services:
  neo4j:
    image: neo4j:5.15.0
    container_name: ai-agent-neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*,gds.*,vectorindex.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      # Vector plugin configurations
      - NEO4J_dbms_security_procedures_allowlist=vectorindex.*
      - NEO4J_server_jvm_additional=-Dneo4j.vector.index=true
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
      # Mount the vector plugin to the plugins directory
      - ./plugins:/plugins
    healthcheck:
      test: ["CMD", "wget", "http://localhost:7474", "-O", "/dev/null", "-q"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: