services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: ai-agent-memgraph
    environment:
      - MEMGRAPH_USER=${MEMGRAPH_USERNAME}
      - MEMGRAPH_PASSWORD=${MEMGRAPH_PASSWORD}
    ports:
      - "7687:7687" # Bolt protocol
      - "7444:7444" # HTTP API
      - "3000:3000" # MemGraph Lab UI
    volumes:
      - memgraph_data:/data
      - memgraph_logs:/var/log/memgraph
      - memgraph_conf:/etc/memgraph
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7444/api/v1/storage/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    command: ["--log-level=TRACE", "--also-log-to-stderr"]

  neo4j-browser:
    image: neo4j:5.15-community
    container_name: ai-agent-neo4j-browser
    ports:
      - "3330:7474"  # Neo4j Browser HTTP
      - "3335:7473"  # Neo4j Browser HTTPS
    environment:
      - NEO4J_dbms_connector_bolt_enabled=false  # Disable Neo4j's own bolt
      - NEO4J_dbms_connector_http_enabled=true
      - NEO4J_dbms_connector_https_enabled=true
    restart: unless-stopped

volumes:
  memgraph_data:
  memgraph_logs:
  memgraph_conf: