name: Deploy to Azure

on:
  push:
    branches: [ RAG ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: dev
  AZURE_RESOURCE_GROUP: GitHub
  AZURE_LOCATION: germanywestcentral

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Add timeout to prevent infinite runs
    steps:
      - uses: actions/checkout@v3
          
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init
        run: |
          cd infra/azure
          terraform init
      
      - name: Terraform Plan
        run: |
          cd infra/azure
          terraform plan -var="environment=${{ env.ENVIRONMENT }}" \
            -var="memgraph_username=${{ secrets.MEMGRAPH_USERNAME }}" \
            -var="memgraph_password=${{ secrets.MEMGRAPH_PASSWORD }}" \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      
      - name: Terraform Apply
        run: |
          cd infra/azure
          terraform apply -auto-approve \
            -var="environment=${{ env.ENVIRONMENT }}" \
            -var="memgraph_username=${{ secrets.MEMGRAPH_USERNAME }}" \
            -var="memgraph_password=${{ secrets.MEMGRAPH_PASSWORD }}" \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      
      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name aks-ai-agent-${{ env.ENVIRONMENT }}
      
      - name: Create K8s Secret for Memgraph
        run: |
          kubectl create secret generic memgraph-credentials \
            --from-literal=username=${{ secrets.MEMGRAPH_USERNAME }} \
            --from-literal=password=${{ secrets.MEMGRAPH_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -
      
      - name: Deploy to AKS
        run: |
          kubectl apply -f infra/k8s/memgraph.yaml
      
      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get services
          kubectl wait --for=condition=ready pod -l app=memgraph --timeout=5m