name: Deploy to Azure

on:
  push:
    branches: [ RAG ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: dev
  AZURE_RESOURCE_GROUP: GitHub
  AZURE_LOCATION: germanywestcentral

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Add timeout to prevent infinite runs
    steps:
      - uses: actions/checkout@v3
          
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init
        run: |
          cd infra/azure
          terraform init
      
      - name: Import Existing Resources
        run: |
          cd infra/azure
          ENVIRONMENT=${{ env.ENVIRONMENT }} \
          SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }} \
          ./import_resources.sh
      
      - name: Terraform Plan
        run: |
          cd infra/azure
          terraform plan -var="environment=${{ env.ENVIRONMENT }}" \
            -var="memgraph_username=${{ secrets.MEMGRAPH_USERNAME }}" \
            -var="memgraph_password=${{ secrets.MEMGRAPH_PASSWORD }}" \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -var="object_id=${{ secrets.AZURE_SP_OBJECT_ID }}"
      
      - name: Terraform Apply
        run: |
          cd infra/azure
          terraform apply -auto-approve \
            -var="environment=${{ env.ENVIRONMENT }}" \
            -var="memgraph_username=${{ secrets.MEMGRAPH_USERNAME }}" \
            -var="memgraph_password=${{ secrets.MEMGRAPH_PASSWORD }}" \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -var="object_id=${{ secrets.AZURE_SP_OBJECT_ID }}"
      
      - name: Get AKS Credentials
        run: |
          # Wait for the AKS cluster to be ready
          echo "Waiting for AKS cluster to be ready..."
          for i in {1..30}; do
            if az aks show --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
                --name aks-ai-agent-${{ env.ENVIRONMENT }} --query "provisioningState" -o tsv | grep -q "Succeeded"; then
              echo "AKS cluster is ready"
              break
            fi
            echo "Waiting for AKS cluster to be ready (attempt $i)..."
            sleep 10
          done
          
          # Get credentials
          az aks get-credentials --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name aks-ai-agent-${{ env.ENVIRONMENT }}
      
      - name: Create K8s Secret for Memgraph
        run: |
          # Check if kubectl is working and the cluster is accessible
          if ! kubectl get nodes &>/dev/null; then
            echo "Cannot connect to Kubernetes cluster. Waiting for it to become available..."
            for i in {1..10}; do
              sleep 15
              if kubectl get nodes &>/dev/null; then
                echo "Successfully connected to Kubernetes cluster"
                break
              fi
              echo "Attempt $i: Still waiting for Kubernetes cluster..."
              if [ $i -eq 10 ]; then
                echo "Failed to connect to Kubernetes cluster after multiple attempts. Continuing anyway..."
              fi
            done
          fi
          
          kubectl create secret generic memgraph-credentials \
            --from-literal=username=${{ secrets.MEMGRAPH_USERNAME }} \
            --from-literal=password=${{ secrets.MEMGRAPH_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -
      
      - name: Deploy to AKS
        run: |
          kubectl apply -f infra/k8s/memgraph.yaml
      
      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get services
          kubectl wait --for=condition=ready pod -l app=memgraph --timeout=5m